version: "3.7"
services:
  db:
    image: mysql/mysql-server:5.7    
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=flaskr
      - MYSQL_USER=flaskr
      - MYSQL_PASSWORD=flaskr
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure
        delay: 5s
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/mysql
    networks:
      - backend

  app:
    image: kevincli/flaskr:latest    
    environment:
      - DATABASE_URL=mysql+pymysql://flaskr:flaskr@db/flaskr
      - DATABASE_MIGRATE=1    
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: continue
      endpoint_mode: vip
      restart_policy: 
        condition: on-failure
        delay: 5s
    networks:
      - frontend
      - backend

  proxy:
    image: nginx:1.16.1-alpine    
    deploy:    
      restart_policy: 
        condition: on-failure
        delay: 20s
    volumes:     
      - type: volume
        source: webstatic
        target: /usr/app/static
        read_only: true
      - type: volume
        source: proxyconf
        target: /etc/nginx/conf.d
        read_only: true
    ports:
      - "80:80"
    networks:
      - frontend

volumes:
  dbdata:
  proxyconf:
  webstatic:

networks:
  frontend:
  backend: 
