version: "3.7"
services:
  db:
    image: mysql/mysql-server:5.7    
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=flaskr
      - MYSQL_USER=flaskr
      - MYSQL_PASSWORD=flaskr
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure
        delay: 5s
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - backend

  app:
    image: kevincli/flaskr:latest    
    environment:
      - DATABASE_URL=mysql+pymysql://flaskr:flaskr@db/flaskr
      - DATABASE_MIGRATE=0    
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        failure_action: rollback
      endpoint_mode: dnsrr
      restart_policy: 
        condition: on-failure
        delay: 5s
    networks:
      - frontend
      - backend

  proxy:
    image: nginx:1.16.1-alpine    
    deploy:    
      restart_policy: 
        condition: on-failure
        delay: 5s
    volumes:
      - c:\ProgramData\nginx\nginx.conf:/etc/nginx/conf.d/default.conf
      - c:\ProgramData\nginx\static:/usr/app/static
    ports:
      - "80:80"
    networks:
      - frontend

volumes:
  dbdata:

networks:
  frontend:
  backend: 